camel:
  springboot:
    # The Camel context name
    name: New API
  component:
    servlet:
      mapping:
        contextPath: /*

# Binding health checks to a different port
management:
  server:
    port: 8081

  # disable all management enpoints except health
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
